### ISSUE TITLE
[iOS Bootcamp] Project 2 - Review my app

### ISSUE THREAD

**Issue by justmisosoup** [littlemisosoup/CodePath-Assignment2-Carousel#1]
My assignment is complete. Please review. cc/ @thecodepath

**Comment by drnick23** [comment]
The purpose of this homework was to leverage views, view properties, and events to create a high fidelity prototype that is difficult to distinguish from a production app. You needed to demonstrate how to work more in depth with scroll views, handle user input to control flow, and show transition states such as the loading indicator.

It looks like you did manage to implement a few more hours between the submission deadline and now, and that you got the animations on scroll working and many of the optionals -- nice!  As a general goal, I would recommend you get all the base requirements done by the end of the weekend to give yourself time to really get more into the optionals. Your code is well structured and I'd love to see more.
